# -*- coding: utf-8 -*-
"""nytUtil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jUQzWYFw98OMs2Ph44lAw_xiTZi8fIiB
"""

# from google.colab import drive
# drive.mount('/content/gdrive')

import pandas as pd
import os
# !pip install plotly

class nytUtil(object):
  def __init__(self,name,dir='/content/gdrive/My Drive/Work/NLP Paul/'):
    self.name = name
    self.dir = dir
    
  def read_comment(self,month,year):
    tmp = pd.read_csv(self.dir+'/Comments'+month+year+'.csv')
    return tmp
  
  
  def read_article(self,month,year):
    tmp = pd.read_csv(self.dir+'/Articles'+month+year+'.csv')
    return tmp
  
  def get_filelist(self):
    filelist = os.listdir(self.dir)
    return filelist
  
  def prepareData(self,article_df, comment_df, only_text_feature=True):
    comment_df = comment_df[comment_df['parentID'] == 0]
    combined_df = pd.merge(comment_df, article_df, on='articleID')

    combined_df = combined_df.drop(['pubDate', 'byline', 'documentType',
                                  'multimedia', 'printPage_y', 'source', 
                                  'typeOfMaterial_y', 'webURL', 'commentType',
                                  'articleWordCount_y', 'commentSequence', 
                                  'commentTitle', 'recommendations'], axis=1)

    combined_df = combined_df.drop(['articleID', 'approveDate', 'articleWordCount_x',
                                  'createDate', 'depth', 'inReplyTo', 'newDesk_x',
                                  'parentID', 'parentUserDisplayName', 'permID', 
                                  'picURL', 'printPage_x', 'recommendedFlag', 
                                  'reportAbuseFlag', 'sectionName_x', 'sharing',
                                  'status', 'timespeople', 'trusted', 'updateDate',
                                  'userDisplayName', 'userID', 'userTitle', 
                                  'userURL', 'typeOfMaterial_x'], axis=1)

    if only_text_feature:
      combined_df = combined_df.drop(['replyCount', 'userLocation', 'headline', 
                                      'keywords', 'newDesk_y', 'sectionName_y'],
                                     axis=1)

    combined_df.editorsSelection = combined_df.editorsSelection == 1
    combined_df.commentID.astype(int)

    print("The shape of final dataset: " + str(combined_df.shape))
    return combined_df.drop(['editorsSelection'], axis=1), combined_df['editorsSelection']  
  
  def plot_pick(self,comment_df):
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    import seaborn as sns
    from plotly.offline import init_notebook_mode, iplot
    init_notebook_mode(connected=True)
    plt.style.use('fivethirtyeight')
#     %matplotlib inline
    
    comment_df.editorsSelection.value_counts()
    mpl.rcParams['figure.figsize'] = (6, 5)
    mpl.rcParams['axes.titlesize'] = 'large'
    mpl.rcParams['axes.labelsize'] = 'medium'
    plt.axis('equal')
    plt.pie(comment_df.editorsSelection.value_counts(), labels=('Not picked', "NYT's pick"));
    plt.title("Selection of comments as NYT's pick");

# test = Util("test")

# tc = test.read_comment("April","2018")
# ta = test.read_article("April","2018")

# combine = test.prepareData(ta,tc,True)

# test.get_filelist()

# test.plot_pick(tc)